"""remove school and add school_name

Revision ID: 78739ac3f8c5
Revises: 29671e982619
Create Date: 2026-06-30 14:01:25.595503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78739ac3f8c5'
down_revision: Union[str, Sequence[str], None] = '29671e982619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('student_profiles_school_id_fkey'), 'student_profiles', type_='foreignkey')
    op.drop_table('schools')
    op.add_column('student_profiles', sa.Column('school_name', sa.String(length=255), nullable=True))
    op.drop_column('student_profiles', 'school_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('student_profiles_school_id_fkey'), 'student_profiles', 'schools', ['school_id'], ['id'], ondelete='SET NULL')
    op.drop_column('student_profiles', 'school_name')
    op.create_table('schools',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('schools_pkey'))
    )
    # ### end Alembic commands ###
